[I 12:46:40.433 NotebookApp] [nb_conda_kernels] enabled, 12 kernels found
[I 12:46:40.977 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 12:46:44.376 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[W 2023-04-01 12:46:51.332 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-04-01 12:46:51.337 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-01 12:46:51.337 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-01 12:46:51.337 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-01 12:46:51.338 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-01 12:46:51.338 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-01 12:46:51.338 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-01 12:46:51.339 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-04-01 12:46:51.346 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2023-04-01 12:46:51.348 LabApp] JupyterLab extension loaded from /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyterlab
[I 2023-04-01 12:46:51.348 LabApp] JupyterLab application directory is /om/user/leokoz8/envs/rnns-of-rnns-env/share/jupyter/lab
[I 12:46:51.354 NotebookApp] Serving notebooks from local directory: /rdma/vast-rdma/vast/fiete/leokoz8/code/rnns-of-rnns
[I 12:46:51.354 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 12:46:51.354 NotebookApp] http://node033:9000/
[I 12:46:51.354 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 12:48:47.213 NotebookApp] 302 GET / (172.16.24.254) 0.990000ms
/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 12:49:03.966 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
Exception in callback <TaskWakeupMethWrapper object at 0x2b2f62acc7f0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b2f62acc7f0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-15' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
Exception in callback <TaskWakeupMethWrapper object at 0x2b2f623a58e0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b2f623a58e0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-14' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /kernel...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
[I 12:49:04.903 NotebookApp] Kernel started: 169a196c-ed0e-4a5e-baea-6a6e243139ff, name: conda-env-leokoz8-rnns-of-rnns-env-py
/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
Exception in callback <TaskWakeupMethWrapper object at 0x2b2f62acc0a0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b2f62acc0a0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-12' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-76' coro=<PeriodicCallback._run() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:694]> is being executed.
Exception in callback <TaskWakeupMethWrapper object at 0x2b2f6234ae50>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b2f6234ae50>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-1' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /static...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-76' coro=<PeriodicCallback._run() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:694]> is being executed.
Exception in callback <TaskWakeupMethWrapper object at 0x2b2f62acc1c0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b2f62acc1c0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-13' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /static...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-76' coro=<PeriodicCallback._run() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:694]> is being executed.
[I 13:09:05.512 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[W 13:09:05.513 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
[I 13:11:04.868 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[W 13:11:04.869 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
[I 13:15:04.873 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[W 13:15:04.874 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
[I 13:17:04.870 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[W 13:17:04.871 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
[I 13:19:04.865 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[W 13:19:04.868 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
[I 13:21:05.484 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[W 13:21:05.485 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
[I 13:39:04.929 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:41:04.577 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 13:41:04.887 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:42:20.402 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 13:42:44.232 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 13:43:05.049 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:45:04.895 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:47:04.856 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:47:07.060 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 13:48:38.444 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 13:49:04.871 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:51:05.499 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:53:05.491 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:55:05.543 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:57:05.487 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 13:59:05.492 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:01:05.484 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:03:05.495 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:05:05.494 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:07:05.564 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:09:04.877 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:11:04.878 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:13:05.530 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:17:05.688 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:19:05.496 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:21:05.494 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:23:05.497 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:25:04.875 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:27:05.502 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:29:05.492 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:31:05.495 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:31:52.121 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 14:33:04.885 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:35:04.894 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:37:04.880 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:39:05.578 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:41:04.887 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:45:04.882 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 14:47:05.531 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:01:05.508 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:03:05.514 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:05:05.521 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:07:05.516 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:09:05.517 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:11:05.512 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:13:04.908 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:15:04.904 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:19:04.899 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:21:04.897 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:27:04.913 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:29:05.639 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:31:05.517 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:33:04.912 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:35:05.519 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:37:04.915 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 15:38:08.813 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 15:39:05.378 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:09:05.058 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:11:05.629 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:13:05.630 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:23:05.013 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:25:05.643 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:27:05.634 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:28:36.924 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:33:05.021 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:33:08.009 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:35:05.678 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:37:05.041 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:40:21.197 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 20:41:05.038 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:41:59.600 NotebookApp] Kernel interrupted: 169a196c-ed0e-4a5e-baea-6a6e243139ff
[I 20:43:05.043 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:47:05.034 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 20:55:05.076 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 21:01:05.087 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 21:02:56.577 NotebookApp] 302 GET / (172.16.24.254) 0.800000ms
[I 21:03:05.677 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 21:05:05.028 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 21:13:05.659 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 21:15:05.090 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[I 21:17:05.659 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
slurmstepd: error: *** JOB 30097444 ON node033 CANCELLED AT 2023-04-02T00:46:31 DUE TO TIME LIMIT ***
