[I 13:28:06.711 NotebookApp] [nb_conda_kernels] enabled, 13 kernels found
[I 13:28:06.864 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 13:28:08.011 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[W 2023-04-30 13:28:09.127 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-04-30 13:28:09.135 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-30 13:28:09.135 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-30 13:28:09.136 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-30 13:28:09.136 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-30 13:28:09.136 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-30 13:28:09.136 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-30 13:28:09.137 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-04-30 13:28:09.150 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2023-04-30 13:28:09.154 LabApp] JupyterLab extension loaded from /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyterlab
[I 2023-04-30 13:28:09.154 LabApp] JupyterLab application directory is /om/weka/fiete/leokoz8/envs/rnns-of-rnns-env/share/jupyter/lab
[I 13:28:09.162 NotebookApp] Serving notebooks from local directory: /net/vast-storage.ib.cluster/scratch/vast/fiete/leokoz8/code/rnns-of-rnns
[I 13:28:09.162 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 13:28:09.162 NotebookApp] http://node058.cm.cluster:9000/
[I 13:28:09.162 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 13:31:07.633 NotebookApp] 302 GET / (172.16.24.254) 1.150000ms
/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 13:31:17.642 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
Exception in callback <TaskWakeupMethWrapper object at 0x2addc93ffc70>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2addc93ffc70>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-1' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
Exception in callback <TaskWakeupMethWrapper object at 0x2addc93ff7f0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2addc93ff7f0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-9' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /kernel...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
[I 13:31:18.044 NotebookApp] Kernel started: 97208795-d89a-4dab-bbdf-97172b95a7a1, name: conda-env-leokoz8-rnns-of-rnns-env-py
/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 13:33:18.066 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:33:18.068 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:35:18.053 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:35:18.054 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:37:18.061 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:37:18.062 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:39:18.062 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:39:18.063 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:41:18.054 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:41:18.055 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:43:18.079 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:43:18.080 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:45:18.055 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:45:18.056 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:47:18.126 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:47:18.128 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:49:18.044 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:49:18.044 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:51:18.054 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:51:18.055 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:53:18.074 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:53:18.075 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:55:18.075 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:55:18.077 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:57:18.341 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:57:18.342 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 13:59:18.058 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 13:59:18.059 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:01:18.078 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:01:18.079 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:03:18.055 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:03:18.057 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:05:18.056 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:05:18.057 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:07:18.064 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:07:18.065 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:08:28.295 NotebookApp] Kernel interrupted: 97208795-d89a-4dab-bbdf-97172b95a7a1
[I 14:08:37.372 NotebookApp] Kernel interrupted: 97208795-d89a-4dab-bbdf-97172b95a7a1
[I 14:09:18.062 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:09:18.063 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:11:18.094 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:11:18.095 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:13:18.066 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:13:18.067 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:15:18.132 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:15:18.133 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:17:18.149 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:17:18.150 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:19:18.080 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:19:18.081 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
Exception in callback <TaskWakeupMethWrapper object at 0x2addc93dddc0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2addc93dddc0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-8' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2581' coro=<PeriodicCallback._run() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:694]> is being executed.
[I 14:23:18.179 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:23:18.180 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:25:18.134 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:25:18.135 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:27:26.333 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:27:26.334 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:29:18.144 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:29:18.145 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:31:26.155 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:31:26.156 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:33:18.087 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:33:18.088 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:35:18.162 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:35:18.163 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:39:26.156 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:39:26.158 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:41:18.147 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:41:18.149 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:43:18.102 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:43:18.103 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:45:18.094 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:45:18.095 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:46:21.990 NotebookApp] Kernel interrupted: 97208795-d89a-4dab-bbdf-97172b95a7a1
[I 14:46:26.295 NotebookApp] Kernel interrupted: 97208795-d89a-4dab-bbdf-97172b95a7a1
[I 14:47:18.089 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:47:18.090 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:48:30.919 NotebookApp] Kernel interrupted: 97208795-d89a-4dab-bbdf-97172b95a7a1
[I 14:49:18.138 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:49:18.159 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:51:18.095 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:51:18.096 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:53:18.090 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:53:18.092 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:55:18.091 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:55:18.092 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:57:18.212 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:57:18.213 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 14:59:18.102 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 14:59:18.103 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 15:01:18.088 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 15:01:18.090 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 15:03:18.111 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 15:03:18.112 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 15:05:18.147 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 15:05:18.149 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 15:07:18.329 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 15:07:18.330 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 15:09:18.105 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 15:09:18.105 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 15:11:21.035 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 15:11:21.036 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 15:11:22.815 NotebookApp] Starting buffering for 97208795-d89a-4dab-bbdf-97172b95a7a1:8c11302b981244b788952b0dd376090b
[W 15:11:30.355 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 19:05:31.052 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 19:05:31.054 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 19:07:31.259 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 19:07:31.260 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 19:09:30.962 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 19:09:30.963 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 19:10:14.797 NotebookApp] Kernel interrupted: 97208795-d89a-4dab-bbdf-97172b95a7a1
[I 19:11:31.004 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 19:11:31.006 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 19:13:31.254 NotebookApp] Saving file at /notebooks/Adaptive Control.ipynb
[W 19:13:31.255 NotebookApp] Notebook notebooks/Adaptive Control.ipynb is not trusted
[I 23:53:57.294 NotebookApp] Starting buffering for 97208795-d89a-4dab-bbdf-97172b95a7a1:5e35cf1512a34371bb9d9a098702590a
slurmstepd: error: *** JOB 30490063 ON node058 CANCELLED AT 2023-05-01T01:28:05 DUE TO TIME LIMIT ***
